### ISSUE TITLE
Possible Incompatibility with Scrolling Speed 2

### ISSUE THREAD

**Issue by OnigiriOni** [ArranzCNL/ImprovedCameraAE#17]
A minor incompatibility arises when using [Scrolling Speed 2](https://www.nexusmods.com/skyrimspecialedition/mods/70455) and setting `Invert Modifier = true`.

This causes the 1st person idle animation for the bow to be enabled as seen here:
![Double Bow](https://i.imgur.com/FHaamIo.png)

I am not sure how this would happen but it seems to be an issue in one of these mods:
- Improved Camera
- Scrolling Speed 2
- SKSE64
- Address Library For SKSE Plugins

And here the extreme accusations:
- SkyUI 5.2
- NL_MCM
- JContainers

**Comment by ArranzCNL** [comment]
Responded on authors page, that invert should be disabled by default, you might get other oddities when using the modifier key but it should resolve itself. The way it currently works is triggering IsScripted flag constantly which can/could potentially break other mods.
