### ISSUE TITLE
Unable to complete the cast of master level (two handed) spells.

### ISSUE THREAD

**Issue by Tytaen** [ArranzCNL/ImprovedCameraAE#18]
Animation comes to a completion but the release never happens. Have to switch spells or weapons in my hands to exit the animation. Works fine with PR1 or no Improved Camera installed.
Only affects the casting in third person. Works as intended in first person.

**Comment by Tytaen** [comment]
Additional information:
Works as intended with bEnableArms=0, but not with it set to 1.

**Comment by ArranzCNL** [comment]
Thanks for the report, has been fixed in next update. Accidently broke it when transferring fixes.
