### ISSUE TITLE
Incompatibility Issue with Skyrim Together Reborn

### ISSUE THREAD

**Issue by Kiraxarik** [ArranzCNL/ImprovedCameraAE#19]
On launch, while Improved Camera AE is installed, Skyrim Together Reborn comes up with an error box saying:

"SwapChain Error Detected:
You are about to crash due to SwapChain issues."

<img width="251" alt="image" src="https://user-images.githubusercontent.com/109116752/180333741-5986bb87-8643-4065-9fba-48b0f972984b.png">

**Comment by ArranzCNL** [comment]
That is not from STR.

SmoothCam and Detection Meter running together can crash your game you have two options:

1. Remove either mod
2. Install ReShade

ReShade fixes issues due to the swapchain.
