### ISSUE TITLE
Game throws error at starting

### ISSUE THREAD

**Issue by kociol21** [ArranzCNL/ImprovedCameraAE#2]
![image](https://user-images.githubusercontent.com/8710354/176027103-53a37e90-f60a-4320-a78c-40f591d05b7b.png)

So this is the error I get when I try to start the game. AE with SKSE 2.0.20.

This is my SKSE plugins list:
ActorLimitFix.dll
AHZmoreHUDInventory.dll
AHZmoreHUDPlugin.dll
ArmorRatingRescaledRemake.dll
AutoInputSwitch.dll
BetterJumpingSE.dll
BladeAndBlunt.dll
BugFixesSSE.dll
CrashLogger.dll
DisplayEnemyLevel.dll
DynamicAnimationReplacer.dll
DynDOLOD.DLL
ENBHelperPlus.dll
ENBHelperSE.dll
ENBInputDisabler.dll
encounter_zones_unlocked.dll
EngineFixes.dll
EquipEnchantmentFix.dll
EVLaS.dll
FaceGenFixes.dll
fiss.dll
FixNotesForSkyUI.dll
ForgetSpell.dll
Fuz Ro D'oh.dll
HandToHand.dll
ImmersiveEquipmentDisplays.dll
ImprovedCameraAE.dll
ImprovementNamesCustomizedSSE.dll
JContainers64.dll
MCMHelper.dll
MoreInformativeConsole.dll
PapyrusUtil.dll
po3_BaseObjectSwapper.dll
po3_ENBLightForEffectShaders.dll
po3_EquipmentToggle.dll
po3_EssentialFavorites.dll
po3_FEC.dll
po3_LockVariations.dll
po3_MagicSneakAttacks.dll
po3_PapyrusExtender.dll
po3_SpellPerkItemDistributor.dll
po3_Tweaks.dll
PriorityMod.dll
Proteus.dll
QUI.dll
QuickLootRE.dll
RememberLockpickAngle.dll
ScaleformTranslationPP.dll
ScrambledBugs.dll
SimpleDualSheath.dll
skee64.dll
SkyrimUncapperAE.dll
SmoothCam.dll
SoakingWet.dll
SSEDisplayTweaks.dll
StormLightning.dll
Thaumaturgy.dll
TrueDirectionalMovement.dll
TrueHUD.dll
Vibrant weapons 1_6_353.dll
WhoseQuestIsItAnyway.dll
YASTM.dll

**Comment by kociol21** [comment]
Nope, same error after disabling Auto Input Switch. Maybe I'll just try to disable one plugin at a time and see which one is the problem.

**Comment by ArranzCNL** [comment]
No, I'm stupid sorry it is something that is changing the flags to the keyboard!
As we set both keyboard and mouse to DISCL_NONEXCLUSIVE | DISCL_FOREGROUND

If wondering why it is so Skyrim broadcasts WinAPI messages to its window which can be captured and processed for the menu.

**Comment by kociol21** [comment]
Oh thanks, this was helpful! So it is this mod:

https://www.nexusmods.com/skyrimspecialedition/mods/3620?tab=posts

It doesn't work with AE but in comment sections one user made unofiicial port requiring Engine Fixes. After disabling it, game starts. I have very floaty movement and my bow flickers but at least it works :) So yeah, issue is solved!

**Comment by ArranzCNL** [comment]
It does the same thing as that mod, so your not losing functionality :)

As for the bow, I know what you mean as it passes into your view from time to time. Default drawn bow looks so rubbish when looking down, you can put it back to this in the ini: bEnableArmsBow=0
