### ISSUE TITLE
Game Crash upon loading whilst mounted on Horse

### ISSUE THREAD

**Issue by killzoms** [ArranzCNL/ImprovedCameraAE#20]
It would appear I have managed to get the game to crash to desktop when loading a save with Immersive Horses
[crash log](https://github.com/ArranzCNL/ImprovedCameraAE/files/9174640/crash.log)
[Save Files](https://github.com/ArranzCNL/ImprovedCameraAE/files/9174642/Save.Files.zip)

Loading save 2(included) will cause the game to crash, while save 1 is before mounting the horse

The crashing seems to be caused by saving while mounted on a horse and then reloading the game

POV does not affect the crashing FYI

**Comment by ArranzCNL** [comment]
I would say its not a issue with Immersive Horses but rather if saved on horse it causes a crash when loading in.

I shall look into it, thanks for the report.

**Comment by ArranzCNL** [comment]
Fixed the crash in next build.

**Needs further investigation:**
Upon entering you will be in third person and cannot re-enter fake first person unless you remount the horse.

**Comment by killzoms** [comment]
tried to provide as much info as i could to get a swift fix for the issue, glad a workaround was provided for now

**Comment by ArranzCNL** [comment]
Fixed additional bug with event not triggering.
