### ISSUE TITLE
Character move like third person when the view in first person

### ISSUE THREAD

**Issue by AnalogKnight** [ArranzCNL/ImprovedCameraAE#22]
I'm not sure if this is a bug as I haven't used this mod in LE. So if I'm wrong, I apologize.
When my camera is in first person, there is a noticeable lag in any movement, and the character doesn't stop immediately when I release the key. This looks like the way to move in third person view.
Is there a way to restore the way the characters move? Or when I pull out my weapon, the original game's first-person view is restored. And when I'm empty handed, I can see my body? I think this is a good approach, since players usually don't focus on their character's body in combat, and laggy movement in combat can be deadly.
I'm sorry my English is not very good.

**Comment by ArranzCNL** [comment]
Known issue fixed as good as possible in upcoming PR.

Limitation is down to hardware, basically input devices running at 125hz (ie keyboard, can be noticed on controllers as well)

**Comment by AnalogKnight** [comment]
Thanks for the great work.
