### ISSUE TITLE
ImprovedCameraAE.dll+000F2C6

### ISSUE THREAD

**Issue by harlequiinh** [ArranzCNL/ImprovedCameraAE#23]
After a couple of hours of playing (16+), the game stopped opening. I started looking for a problem, removed mods (both animation and graphic). Nothing helped. After a couple of hours of disassembly with mods, we managed to start the game, but not for long. Literally after starting a clean save, I completed the quest with the first dragon, saved and exited. Then CTD started again. I could not find the culprit and decided to say Crash Logger. It indicates that Improved Camera is dropping the game for me. There are options that I did wrong with my list of mods?

SKSE64 LOG 
[skse64.log](https://github.com/ArranzCNL/ImprovedCameraAE/files/9274849/skse64.log)

Crash Logger
[crash-2022-08-06-10-29-53.log](https://github.com/ArranzCNL/ImprovedCameraAE/files/9274850/crash-2022-08-06-10-29-53.log)

I tried to run it without smoothcam and TDM (by the way, at the very beginning everything worked as it should, no crashes).

MODLIST 
[modlist.txt](https://github.com/ArranzCNL/ImprovedCameraAE/files/9274860/modlist.txt)

ESPLIST 
[loadorder.txt](https://github.com/ArranzCNL/ImprovedCameraAE/files/9274861/loadorder.txt)

**Comment by lutcyus** [comment]
Если необходимо, настройки ICAE.
[ImprovedCameraAE.txt](https://github.com/ArranzCNL/ImprovedCameraAE/files/9274866/ImprovedCameraAE.txt)

**Comment by ArranzCNL** [comment]
Completed the quest with the first dragon? Helgen?

It is sounding like a fix I've applied but currently not released. There was a null ICamera mainly happened if you saved on Dragon/Horse and thinking about it I need to check the Cartride where it saves at the end to check relevant events are processed correctly.

Looking at the Crash Logger, yes it is a fix I've applied just currently not released.


Feel free to re-open this if it occurs again on the next release.

**Comment by harlequiinh** [comment]
Yea, dragon rising. I looked at my saves, on all the saves I was saved on a horse. From what you're saying, that's what's breaking my saves. I'll try clearing my saves with ReSaver and booting without a ICAE. If the saves are restored without a horse, then I will know that it is better to leave the horse before saving. Thanks for the quick response!

**Comment by harlequiinh** [comment]
And yes, they were horses. Thanks for helping me figure it out, I was already frustrated that I had lost all the progress I had made. I know it's none of my business, but I would add a horse/dragon line to Reddit so people don't have to worry about what it is and be more careful.
Thank you very much again!

**Comment by ArranzCNL** [comment]
It seems to be far and few inbetween people saving on horse... however I had to do additional fixes to them so you are actually in first person again if you saved in that state.

What you can do, don't have IC active jump off your horse and save then you can reactivate IC. You should be fine then until next release hoping today/tomorrow so not long to wait! :)
