### ISSUE TITLE
bug when entering furniture

### ISSUE THREAD

**Issue by zhongjiedong** [ArranzCNL/ImprovedCameraAE#24]
https://gfycat.com/edibletidyhart

gif speaks for itself XD

**Comment by ArranzCNL** [comment]
There is a stealth update coming within an hour or 2.
All events working and fixed the events when disabled or not recognised. (As seen in your gif :D)

Currently finishing off some work on the menu before releasing.

**Comment by zhongjiedong** [comment]
Just realised i posted this in wrong repo, this bug was experienced in the SE version if that makes any difference

**Comment by ArranzCNL** [comment]
Stealth Update Applied.
