### ISSUE TITLE
Bug in immersive Interactions - Animated Actions

### ISSUE THREAD

**Issue by zyf2008Neptune** [ArranzCNL/ImprovedCameraAE#28]
When using highest level 3rd person view, some animations will switch to 1st person view.

**Comment by ArranzCNL** [comment]
More than likely unavoidable but need to know exactly which animations.

Tested picking plants etc everything seemed normal.

**Comment by zyf2008Neptune** [comment]
Zoom out is ok bug zoom in is not (picking plants and touch body/chest)

**Comment by ArranzCNL** [comment]
Immersive Interactions you need to set it on Force Third Person and make sure to turn off Puzzles which affects pulling levers etc.
