### ISSUE TITLE
Can't open game 1.6.353

### ISSUE THREAD

**Issue by Zarvaxxxx** [ArranzCNL/ImprovedCameraAE#31]
Here is the error I recieve. 

![Screenshot 2022-12-06 002159](https://user-images.githubusercontent.com/120328468/206917398-bcea6d22-a375-49f8-a8a5-55b91cec92c0.png)

**Comment by Octobread** [comment]
Try the version from the [SE repo](https://github.com/ArranzCNL/ImprovedCameraSE). According to [the release page](https://github.com/ArranzCNL/ImprovedCameraAE/releases) this one seems to be deprecated:

>This repo will be removed in the future due to being surplus to requirements:
> For latest AE build please use:
>[ImprovedCameraSE](https://github.com/ArranzCNL/ImprovedCameraSE/releases/tag/v1.0.0)

The SE version should also work for the Anniversary edition. I'm also currently running it with `1.6.353`.

**Comment by ArranzCNL** [comment]
As Octobread said, I forget to actually check here. I should really close it down completely since it is covered in the SE branch.
