### ISSUE TITLE
Unable to ground target conjure spells in first person. (sometimes)

### ISSUE THREAD

**Issue by Tytaen** [ArranzCNL/ImprovedCameraAE#8]
I can't narrow down any exact repeatable to get this to work or not work.

**Comment by Tytaen** [comment]
Sorry I haven't responded sooner, github is confusing to me :)

After further testing it seems to only occur in indoor cells (draugr crypts and such) and affects conjure summon spells, teleport, blink and rune spells that I've tested so far. It seems to act like all surfaces are "out of range".

**Comment by ArranzCNL** [comment]
Which custom mod(s) are they from, as I see teleport and blink are not standard skyrim spells?

**Comment by Tytaen** [comment]
blink and teleport are from Psijic Teleport Spells; https://www.nexusmods.com/skyrimspecialedition/mods/5643

**Comment by ArranzCNL** [comment]
Ok thanks I'll install that later for AE and take a look.

**Comment by Tytaen** [comment]
The only mod that I know of that I run that affects targetting is trueHUD, a part of the smoothcam/true directional movement family. If I need to upload a .txt file with my load order I will, but I'll leave that up to request. Elsewise I just wanted to take a moment to thank you and your team for your work on this mod. It once again has its place in my permanent load order even with this small issue. In around 200 hours of testing that's the only thing I've noticed that could potentially pertain to the scope of this mod. (would have posted on reddit instead but simply can't figure out how)
