### ISSUE TITLE
Mouse not bounded to main screen with dual monitor setup

### ISSUE THREAD

**Issue by z3psk1** [ArranzCNL/ImprovedCameraAE#9]
When the mod is active, mouse leaves primary screen on to secondary screen, tabbing out when clicking outside.

**Comment by ArranzCNL** [comment]
Even happens on a single screen, but that is due to carrying out tests against ENB.

Shall change where the mouse clipping occurs, placed inside of DInput hook currently which is bad.

**Comment by ArranzCNL** [comment]
Issue is resolved moved the logic to WindowSystem and added additional force lockon startup.

Fixed in PR2.
